travis:
  secure:
    BINSTAR_TOKEN: WDLPYtTCihiukVph/QxVFYt5pVYEe7ofdg9xb2wiA8fH+ypb2KVVfpEymOIBT+8oYbHET9uUNrjO2NvlHKFMh9cQNLv24V0Jmif85fRZhdrzBMPejROd73rqhYYXTLlGBUeHdTczOOzGiO5CmtC/OxJWFUL+Tx977Qbr23javGlNf+mONCL6U2/hnvQRbY6u+ZGc6iYxrkGHWgUXgZFiUZafIzC3xtgJ+DRlK+Jz+2AtKaImnKIsUT+LW+tPM7DdzEhStzROiw5X0l0SLDx99IDYNn7N2fa2ddBVROXwxm5W1/U6y49ONNr30srb6TuxPztOPksNaBg3fllYpFrfp/x6iJJE87K99x2XPc+HU3KykIVTIt4/rilVVUAufmRO8qneqr1dDTyG1hlqgCxRR6ZC3RT//QS2zYRHWJEQNHsYv/YOVBu6wd6XGNkCY1gueWXO2aZwIbvY3aNW2xUNm0Y1lxhka7eJ/2yaWswqkHbrYjny7MShfOI71ve4ctoharRw9OapcdPFwFMpzvEche7oQpU1RL+nPubwmguN2DMfSBUqddrwM9LMmdFjmp5KJidA7HVkodH4rPbSYQhno0Bmj87CWF5+Kw08bQ8WZkP4yEBqGPY23xh4NUf91cM8y1ssohC9btyxtHBLcMCB70HqC+wfCf19t9V12A6L/Bo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
